### ISSUE TITLE
ERROR: Routes.getReport | TypeError: Cannot read property 'buy' of undefined

### ISSUE THREAD

**Issue by incognico** [igoramadas/pandagainz#5]
Bekomme folgenden Fehler: `ERROR: Routes.getReport | TypeError: Cannot read property 'buy' of undefined`

**Comment by igoramadas** [comment]
Will be fixed this week, thanks for reporting it.

**Comment by igoramadas** [comment]
Fixed.

https://github.com/igoramadas/pandagainz/commit/e88bad7cd34fad07e5de0a2fe4c784fb1a5e72ef
